### ISSUE TITLE
Laptime on Austria is about 51s, but the laptime in paper is 40s

### ISSUE THREAD

**Issue by YYan99** [CPS-TUWien/racing_dreamer#3] opened 2021-05-03 06:34 UTC
I run the checkpoint(austria) in code by using simulator, but laptime is only 53s, and sometimes the racecar collided. Then I trained the dreamer on austria for 3.7M,  the horizon is 50, but in simulator the laptime is 51s. However, the laptime in your paper is about 40s. Why? 
![image](https://user-images.githubusercontent.com/74341446/116847152-8d066380-ac1c-11eb-8eee-a86dc43974e3.png)

**Comment by luigiberducci** [comment] 2021-05-03 07:03
Could you please report the checkpoint you used for test? I am wondering if the parameters configuration is the same. Look forward to your answer!

**Comment by YYan99** [comment] 2021-05-03 07:15
> Could you please report the checkpoint you used for test? I am wondering if the parameters configuration is the same. Look forward to your answer!

Thank you for your reply! 
The first checkpoint is in racing_dreamer/ros_agent/checkpoints/austria_dreamer/ 
The second is below:
[best.zip](https://github.com/CPS-TUWien/racing_dreamer/files/6413331/best.zip)

**Comment by luigiberducci** [comment] 2021-05-03 09:50
Thanks for your question!

The checkpoint you are referring to has been adopted in the preliminary test on ROS, transferring the agent from simulation to the real car.
This is not the final version and quite a bit outdated. We would recommend you to refer to the official logs mentioned in the paper, and reported [here](https://zenodo.org/record/4588599)

There, you can find a directory with all the checkpoints used to produce the plots.
Since the logs are quite large, we created [this checkpoint](https://owncloud.tuwien.ac.at/index.php/s/jxUswCWnlPpNd0a) to give you access to the models used to produce the logs. Hope it helps!

Also, to ensure we are reproducing the same results, we just updated the module `dreamer/evaluations` in this repo. To test a given checkpoint, you can run the following script:
```
python evaluations/run_evaluation.py --agent dreamer
            --obs_type lidar --checkpoint_dir place-here-the-path-to-the-checkpoint-dir
            --trained_on austria --tracks austria
            --eval_episodes 10 --outdir logs/evaluations
```
Please ensure to run this from the "dreamer" directory and to have it in your PYTHONPATH.
This script will run 10 evaluations episodes by using each checkpoint in the checkpoint directory which corresponds to the following configuration:
1) agent is "dreamer",
2) it has been trained on Austria,
3) it has been trained with LiDAR reconstruction.

We just repeated the evaluations, and we confirm that by considering the episodes in which dreamer achieve full-lap, the lap-time is about 40 seconds.
To confirm this, we also add it in the shared log directory. You can find the videos in `log_eval_20210503/videos/`.
For example, look at any videos from `checkpoint_3` which is the one with more stable performances.

Concerning the training, there is probably some mismatch in the parameters used.
For example, we used `action_repeat=8` as reported in the appendix on [arxiv](https://arxiv.org/pdf/2103.04909.pdf).
Please, let us know if you continue facing the same issue when training in the same parameters configuration.

Thanks!

**Comment by YYan99** [comment] 2021-05-05 06:09
Thanks for your patience!

I have exported the PYTHONPATH :
`export PYTHONPATH="home/yy/racing_dreamer/dreamer:$PYTHONPATH"
`

but when I running the script, there is an error as follows:
```
[Info] Found 3 checkpoint
Traceback (most recent call last):
  File "dreamer/evaluations/run_evaluation.py", line 119, in <module>
    main(args)
  File "dreamer/evaluations/run_evaluation.py", line 88, in main
    agent = RacingAgent(args.agent, checkpoints[0], obs_type=args.obs_type, action_dist=args.action_dist)
  File "/home/yy/racing_dreamer/dreamer/evaluations/racing_agent.py", line 21, in __init__
    from .dream import RacingDreamer
ImportError: attempted relative import with no known parent package
```

Then I delete the dot`.` before `dream`, the result as follows:
```
[Info] Found 3 checkpoint
Traceback (most recent call last):
  File "dreamer/evaluations/run_evaluation.py", line 119, in <module>
    main(args)
  File "dreamer/evaluations/run_evaluation.py", line 88, in main
    agent = RacingAgent(args.agent, checkpoints[0], obs_type=args.obs_type, action_dist=args.action_dist)
  File "/home/yy/racing_dreamer/dreamer/evaluations/racing_agent.py", line 21, in __init__
    from dream import RacingDreamer
  File "/home/yy/racing_dreamer/dreamer/evaluations/dream/__init__.py", line 1, in <module>
    from .racing_dreamer import RacingDreamer
  File "/home/yy/racing_dreamer/dreamer/evaluations/dream/racing_dreamer.py", line 4, in <module>
    import dreamer.callbacks as callbacks
ModuleNotFoundError: No module named 'dreamer'
```

Could you please tell me where is the problem? Thanks!

**Comment by luigiberducci** [comment] 2021-05-05 07:05
Sorry Yan, yesterday I changed some imports and filepaths but I forgot to push the changes in the current repo.
Please, try again, it should be fixed.

**Comment by YYan99** [comment] 2021-05-08 11:53
I try it again,the result is as follows:
```
Traceback (most recent call last):
  File "evaluations/run_evaluation.py", line 119, in <module>
    main(args)
  File "evaluations/run_evaluation.py", line 88, in main
    agent = RacingAgent(args.agent, checkpoints[0], obs_type=args.obs_type, action_dist=args.action_dist)
  File "/home/yy/racing_dreamer/dreamer/evaluations/racing_agent.py", line 22, in __init__
    self._agent = RacingDreamer(checkpoint_path=checkpoint_path, **kwargs)
  File "/home/yy/racing_dreamer/dreamer/evaluations/dreamer/racing_dreamer.py", line 46, in __init__
    super().__init__(config, datadir, actspace, obspace, writer=None)
  File "/home/yy/racing_dreamer/dreamer/models.py", line 39, in __init__
    self._build_model()
  File "/home/yy/racing_dreamer/dreamer/models.py", line 187, in _build_model
    self.train(next(self._dataset))
  File "/home/yy/anaconda2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 824, in __call__
    return self._python_function(*args, **kwds)
  File "/home/yy/anaconda2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3882, in bound_method_wrapper
    return wrapped_fn(weak_instance(), *args, **kwargs)
  File "/home/yy/racing_dreamer/dreamer/models.py", line 89, in train
    self._strategy.experimental_run_v2(self._train, args=(data, log_images))
AttributeError: 'MirroredStrategy' object has no attribute 'experimental_run_v2'

```
Then I change `experimental_run_v2` with `run`,it works.

I have changed the parameters that you mentioned ,and I get the result which is same as the result in the paper. However, when I use the checkpoints(in`checkpoints/best`) on ROS(`ros_agent/checkpoints`), it doesn't perform well. 

How to use the `.pkl` file on ROS? Is there some problems in my process of simulation?

Thanks!

**Comment by luigiberducci** [comment] 2021-05-12 10:14
Hi Yan,
Have you tried to run the code using the docker image provided? I am not facing the same error, so it could be something specific to your configuration (maybe related to tf or tf-probability).

Concerning the transfer in ROS, we would need more information on how you are integrating the checkpoint model and how you are simulating it.
As far as I understand, you are using the checkpoint of the agent trained in Austria. In our experiments, we transfer to real-car the agent trained in Treitlstrasse, which is the track existing in our university. Moreover, we adapted the model's output to the car configuration by integrating the motor force to obtain the desired speed. This was related to our car setup.

Best regards,
Luigi

**Comment by lmc19970711** [comment] 2021-05-14 03:29
Hi Yan, I have some questions. I would like to ask you. My WeChat is Lumc0711.

**Closed as completed** 2021-05-14 15:54 UTC

**Comment by YYan99** [comment] 2021-05-23 13:26
Hi Luigi,
I changed the `AGENT_CHECKPOINT=trierlstrasse_dreamer` with `AGENT_CHECKPOINT=austria_dreamer` in `/ros_agent/Makefile`, but there were some errors:
```
ValueError: The two structures don't have the same nested structure.
...
Entrire first structure:
(., ., ., ., ., ., ., ., ., ., ., ., ., .)
Entrire second structure:
(., ., ., ., ., ., ., ., ., .)
```
Are you facing the same error before? Would you please test the code in `/ros_agent` again?

Thanks!
 
Best regards,
Yan

**Comment by oddest-prime** [comment] 2021-06-01 13:01
Hi Yan!

What command (what make target(s)) did you use? Did other checkpoints work properly on your system?

best regards,
